### ISSUE TITLE
Allow for multiple Slack orgs/accounts

### ISSUE THREAD

**Issue by sknep** [micthiesen/spotify-my-slack#17]
Would love to have this update more than one Slack acct (I have several).  Great work on this, and thanks!

**Comment by micthiesen** [comment]
You should be able to do this now. If you click "SIGN OUT", then connection your Spotify account then connect _any_ Slack account, a new link will be created between whichever 2 accounts you connect.

And thanks! Status updates are slow right now because Spotify is throttling the application's requests pretty hard. But it's still working alright.

**Comment by micthiesen** [comment]
Closing this as I believe it's already possible. Let me know if there are any issues.
